name: to releases
on:
  workflow_dispatch:
  schedule:
      # 每月30日00:00运行. 时间设置参考： http://crontab.guru
      - cron: '0 0 30 * *'
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-kernel:
    uses: ./.github/workflows/build-oneplus-6-6t-ksu-kernel.yml
    secrets: inherit

  release:
    needs: 
      - build-kernel

      - name: GetTime
        id: get_time
        run: |
          echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT

      runs-on: ubuntu-latest
        steps:
          - name: Download artifacts
            uses: actions/download-artifact@v3
          - name: Zip AnyKernel3
            run: |
              cd AnyKernel3_Backup
              zip -r9 Radioactive_kernel_op6-KSU-${{ steps.get_time.outputs.TIME }}* >/dev/null
              cd ..
              mv AnyKernel3_Backup/Radioactive_kernel_op6-KSU-${{ steps.get_time.outputs.TIME }}.zip Radioactive_kernel_op6-KSU-${{ steps.get_time.outputs.TIME }}.zip
              rm -rf AnyKernel3_Backup/Image.gz-dtb
      
              
              
        - name: Display structure of downloaded files
              run: ls -R
      
        - name: release
            uses: softprops/action-gh-release@v1
            with:
              files: |
                Radioactive_kernel_op6-KSU-${{ steps.get_time.outputs.TIME }}.zip
                  